// Mocks generated by Mockito 5.4.6 from annotations
// in dadytube/test/services/video_cache_service_cache_video_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:collection' as _i7;

import 'package:http_parser/http_parser.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:youtube_explode_dart/src/channels/channels.dart' as _i4;
import 'package:youtube_explode_dart/src/playlists/playlist_client.dart' as _i3;
import 'package:youtube_explode_dart/src/reverse_engineering/models/fragment.dart'
    as _i15;
import 'package:youtube_explode_dart/src/search/search_client.dart' as _i5;
import 'package:youtube_explode_dart/src/videos/streams/mixins/hls_stream_info.dart'
    as _i14;
import 'package:youtube_explode_dart/src/videos/streams/streams.dart' as _i6;
import 'package:youtube_explode_dart/src/videos/video_client.dart' as _i2;
import 'package:youtube_explode_dart/src/videos/video_id.dart' as _i8;
import 'package:youtube_explode_dart/src/videos/youtube_api_client.dart'
    as _i12;
import 'package:youtube_explode_dart/src/youtube_explode_base.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVideoClient_0 extends _i1.SmartFake implements _i2.VideoClient {
  _FakeVideoClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistClient_1 extends _i1.SmartFake
    implements _i3.PlaylistClient {
  _FakePlaylistClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChannelClient_2 extends _i1.SmartFake implements _i4.ChannelClient {
  _FakeChannelClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchClient_3 extends _i1.SmartFake implements _i5.SearchClient {
  _FakeSearchClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamManifest_4 extends _i1.SmartFake
    implements _i6.StreamManifest {
  _FakeStreamManifest_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnmodifiableListView_5<E> extends _i1.SmartFake
    implements _i7.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVideoId_6 extends _i1.SmartFake implements _i8.VideoId {
  _FakeVideoId_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_7 extends _i1.SmartFake implements Uri {
  _FakeUri_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamContainer_8 extends _i1.SmartFake
    implements _i6.StreamContainer {
  _FakeStreamContainer_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSize_9 extends _i1.SmartFake implements _i6.FileSize {
  _FakeFileSize_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBitrate_10 extends _i1.SmartFake implements _i6.Bitrate {
  _FakeBitrate_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVideoResolution_11 extends _i1.SmartFake
    implements _i6.VideoResolution {
  _FakeVideoResolution_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFramerate_12 extends _i1.SmartFake implements _i6.Framerate {
  _FakeFramerate_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaType_13 extends _i1.SmartFake implements _i9.MediaType {
  _FakeMediaType_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [YoutubeExplode].
///
/// See the documentation for Mockito's code generation for more information.
class MockYoutubeExplode extends _i1.Mock implements _i10.YoutubeExplode {
  @override
  _i2.VideoClient get videos =>
      (super.noSuchMethod(
            Invocation.getter(#videos),
            returnValue: _FakeVideoClient_0(this, Invocation.getter(#videos)),
            returnValueForMissingStub: _FakeVideoClient_0(
              this,
              Invocation.getter(#videos),
            ),
          )
          as _i2.VideoClient);

  @override
  _i3.PlaylistClient get playlists =>
      (super.noSuchMethod(
            Invocation.getter(#playlists),
            returnValue: _FakePlaylistClient_1(
              this,
              Invocation.getter(#playlists),
            ),
            returnValueForMissingStub: _FakePlaylistClient_1(
              this,
              Invocation.getter(#playlists),
            ),
          )
          as _i3.PlaylistClient);

  @override
  _i4.ChannelClient get channels =>
      (super.noSuchMethod(
            Invocation.getter(#channels),
            returnValue: _FakeChannelClient_2(
              this,
              Invocation.getter(#channels),
            ),
            returnValueForMissingStub: _FakeChannelClient_2(
              this,
              Invocation.getter(#channels),
            ),
          )
          as _i4.ChannelClient);

  @override
  _i5.SearchClient get search =>
      (super.noSuchMethod(
            Invocation.getter(#search),
            returnValue: _FakeSearchClient_3(this, Invocation.getter(#search)),
            returnValueForMissingStub: _FakeSearchClient_3(
              this,
              Invocation.getter(#search),
            ),
          )
          as _i5.SearchClient);

  @override
  set videos(_i2.VideoClient? value) => super.noSuchMethod(
    Invocation.setter(#videos, value),
    returnValueForMissingStub: null,
  );

  @override
  set playlists(_i3.PlaylistClient? value) => super.noSuchMethod(
    Invocation.setter(#playlists, value),
    returnValueForMissingStub: null,
  );

  @override
  set channels(_i4.ChannelClient? value) => super.noSuchMethod(
    Invocation.setter(#channels, value),
    returnValueForMissingStub: null,
  );

  @override
  set search(_i5.SearchClient? value) => super.noSuchMethod(
    Invocation.setter(#search, value),
    returnValueForMissingStub: null,
  );

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StreamClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamClient extends _i1.Mock implements _i6.StreamClient {
  @override
  _i11.Future<_i6.StreamManifest> getManifest(
    dynamic videoId, {
    bool? fullManifest = false,
    List<_i12.YoutubeApiClient>? ytClients,
    bool? requireWatchPage = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getManifest,
              [videoId],
              {
                #fullManifest: fullManifest,
                #ytClients: ytClients,
                #requireWatchPage: requireWatchPage,
              },
            ),
            returnValue: _i11.Future<_i6.StreamManifest>.value(
              _FakeStreamManifest_4(
                this,
                Invocation.method(
                  #getManifest,
                  [videoId],
                  {
                    #fullManifest: fullManifest,
                    #ytClients: ytClients,
                    #requireWatchPage: requireWatchPage,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.StreamManifest>.value(
              _FakeStreamManifest_4(
                this,
                Invocation.method(
                  #getManifest,
                  [videoId],
                  {
                    #fullManifest: fullManifest,
                    #ytClients: ytClients,
                    #requireWatchPage: requireWatchPage,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.StreamManifest>);

  @override
  _i11.Future<String> getHttpLiveStreamUrl(_i8.VideoId? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#getHttpLiveStreamUrl, [videoId]),
            returnValue: _i11.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#getHttpLiveStreamUrl, [videoId]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#getHttpLiveStreamUrl, [videoId]),
              ),
            ),
          )
          as _i11.Future<String>);

  @override
  _i11.Stream<List<int>> get(_i6.StreamInfo? streamInfo) =>
      (super.noSuchMethod(
            Invocation.method(#get, [streamInfo]),
            returnValue: _i11.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i11.Stream<List<int>>.empty(),
          )
          as _i11.Stream<List<int>>);
}

/// A class which mocks [StreamManifest].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamManifest extends _i1.Mock implements _i6.StreamManifest {
  @override
  _i7.UnmodifiableListView<_i6.StreamInfo> get streams =>
      (super.noSuchMethod(
            Invocation.getter(#streams),
            returnValue: _FakeUnmodifiableListView_5<_i6.StreamInfo>(
              this,
              Invocation.getter(#streams),
            ),
            returnValueForMissingStub:
                _FakeUnmodifiableListView_5<_i6.StreamInfo>(
                  this,
                  Invocation.getter(#streams),
                ),
          )
          as _i7.UnmodifiableListView<_i6.StreamInfo>);

  @override
  _i7.UnmodifiableListView<_i6.AudioStreamInfo> get audio =>
      (super.noSuchMethod(
            Invocation.getter(#audio),
            returnValue: _FakeUnmodifiableListView_5<_i6.AudioStreamInfo>(
              this,
              Invocation.getter(#audio),
            ),
            returnValueForMissingStub:
                _FakeUnmodifiableListView_5<_i6.AudioStreamInfo>(
                  this,
                  Invocation.getter(#audio),
                ),
          )
          as _i7.UnmodifiableListView<_i6.AudioStreamInfo>);

  @override
  _i7.UnmodifiableListView<_i6.VideoStreamInfo> get video =>
      (super.noSuchMethod(
            Invocation.getter(#video),
            returnValue: _FakeUnmodifiableListView_5<_i6.VideoStreamInfo>(
              this,
              Invocation.getter(#video),
            ),
            returnValueForMissingStub:
                _FakeUnmodifiableListView_5<_i6.VideoStreamInfo>(
                  this,
                  Invocation.getter(#video),
                ),
          )
          as _i7.UnmodifiableListView<_i6.VideoStreamInfo>);

  @override
  _i7.UnmodifiableListView<_i6.MuxedStreamInfo> get muxed =>
      (super.noSuchMethod(
            Invocation.getter(#muxed),
            returnValue: _FakeUnmodifiableListView_5<_i6.MuxedStreamInfo>(
              this,
              Invocation.getter(#muxed),
            ),
            returnValueForMissingStub:
                _FakeUnmodifiableListView_5<_i6.MuxedStreamInfo>(
                  this,
                  Invocation.getter(#muxed),
                ),
          )
          as _i7.UnmodifiableListView<_i6.MuxedStreamInfo>);

  @override
  _i7.UnmodifiableListView<_i6.AudioOnlyStreamInfo> get audioOnly =>
      (super.noSuchMethod(
            Invocation.getter(#audioOnly),
            returnValue: _FakeUnmodifiableListView_5<_i6.AudioOnlyStreamInfo>(
              this,
              Invocation.getter(#audioOnly),
            ),
            returnValueForMissingStub:
                _FakeUnmodifiableListView_5<_i6.AudioOnlyStreamInfo>(
                  this,
                  Invocation.getter(#audioOnly),
                ),
          )
          as _i7.UnmodifiableListView<_i6.AudioOnlyStreamInfo>);

  @override
  _i7.UnmodifiableListView<_i6.VideoOnlyStreamInfo> get videoOnly =>
      (super.noSuchMethod(
            Invocation.getter(#videoOnly),
            returnValue: _FakeUnmodifiableListView_5<_i6.VideoOnlyStreamInfo>(
              this,
              Invocation.getter(#videoOnly),
            ),
            returnValueForMissingStub:
                _FakeUnmodifiableListView_5<_i6.VideoOnlyStreamInfo>(
                  this,
                  Invocation.getter(#videoOnly),
                ),
          )
          as _i7.UnmodifiableListView<_i6.VideoOnlyStreamInfo>);

  @override
  _i7.UnmodifiableListView<_i14.HlsStreamInfo> get hls =>
      (super.noSuchMethod(
            Invocation.getter(#hls),
            returnValue: _FakeUnmodifiableListView_5<_i14.HlsStreamInfo>(
              this,
              Invocation.getter(#hls),
            ),
            returnValueForMissingStub:
                _FakeUnmodifiableListView_5<_i14.HlsStreamInfo>(
                  this,
                  Invocation.getter(#hls),
                ),
          )
          as _i7.UnmodifiableListView<_i14.HlsStreamInfo>);
}

/// A class which mocks [MuxedStreamInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMuxedStreamInfo extends _i1.Mock implements _i6.MuxedStreamInfo {
  @override
  _i8.VideoId get videoId =>
      (super.noSuchMethod(
            Invocation.getter(#videoId),
            returnValue: _FakeVideoId_6(this, Invocation.getter(#videoId)),
            returnValueForMissingStub: _FakeVideoId_6(
              this,
              Invocation.getter(#videoId),
            ),
          )
          as _i8.VideoId);

  @override
  int get tag =>
      (super.noSuchMethod(
            Invocation.getter(#tag),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  Uri get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _FakeUri_7(this, Invocation.getter(#url)),
            returnValueForMissingStub: _FakeUri_7(
              this,
              Invocation.getter(#url),
            ),
          )
          as Uri);

  @override
  _i6.StreamContainer get container =>
      (super.noSuchMethod(
            Invocation.getter(#container),
            returnValue: _FakeStreamContainer_8(
              this,
              Invocation.getter(#container),
            ),
            returnValueForMissingStub: _FakeStreamContainer_8(
              this,
              Invocation.getter(#container),
            ),
          )
          as _i6.StreamContainer);

  @override
  _i6.FileSize get size =>
      (super.noSuchMethod(
            Invocation.getter(#size),
            returnValue: _FakeFileSize_9(this, Invocation.getter(#size)),
            returnValueForMissingStub: _FakeFileSize_9(
              this,
              Invocation.getter(#size),
            ),
          )
          as _i6.FileSize);

  @override
  _i6.Bitrate get bitrate =>
      (super.noSuchMethod(
            Invocation.getter(#bitrate),
            returnValue: _FakeBitrate_10(this, Invocation.getter(#bitrate)),
            returnValueForMissingStub: _FakeBitrate_10(
              this,
              Invocation.getter(#bitrate),
            ),
          )
          as _i6.Bitrate);

  @override
  String get audioCodec =>
      (super.noSuchMethod(
            Invocation.getter(#audioCodec),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#audioCodec),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#audioCodec),
            ),
          )
          as String);

  @override
  String get videoCodec =>
      (super.noSuchMethod(
            Invocation.getter(#videoCodec),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#videoCodec),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#videoCodec),
            ),
          )
          as String);

  @override
  String get videoQualityLabel =>
      (super.noSuchMethod(
            Invocation.getter(#videoQualityLabel),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#videoQualityLabel),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#videoQualityLabel),
            ),
          )
          as String);

  @override
  _i6.VideoQuality get videoQuality =>
      (super.noSuchMethod(
            Invocation.getter(#videoQuality),
            returnValue: _i6.VideoQuality.unknown,
            returnValueForMissingStub: _i6.VideoQuality.unknown,
          )
          as _i6.VideoQuality);

  @override
  _i6.VideoResolution get videoResolution =>
      (super.noSuchMethod(
            Invocation.getter(#videoResolution),
            returnValue: _FakeVideoResolution_11(
              this,
              Invocation.getter(#videoResolution),
            ),
            returnValueForMissingStub: _FakeVideoResolution_11(
              this,
              Invocation.getter(#videoResolution),
            ),
          )
          as _i6.VideoResolution);

  @override
  _i6.Framerate get framerate =>
      (super.noSuchMethod(
            Invocation.getter(#framerate),
            returnValue: _FakeFramerate_12(this, Invocation.getter(#framerate)),
            returnValueForMissingStub: _FakeFramerate_12(
              this,
              Invocation.getter(#framerate),
            ),
          )
          as _i6.Framerate);

  @override
  List<_i15.Fragment> get fragments =>
      (super.noSuchMethod(
            Invocation.getter(#fragments),
            returnValue: <_i15.Fragment>[],
            returnValueForMissingStub: <_i15.Fragment>[],
          )
          as List<_i15.Fragment>);

  @override
  _i9.MediaType get codec =>
      (super.noSuchMethod(
            Invocation.getter(#codec),
            returnValue: _FakeMediaType_13(this, Invocation.getter(#codec)),
            returnValueForMissingStub: _FakeMediaType_13(
              this,
              Invocation.getter(#codec),
            ),
          )
          as _i9.MediaType);

  @override
  String get qualityLabel =>
      (super.noSuchMethod(
            Invocation.getter(#qualityLabel),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#qualityLabel),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#qualityLabel),
            ),
          )
          as String);

  @override
  bool get isThrottled =>
      (super.noSuchMethod(
            Invocation.getter(#isThrottled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
