// Mocks generated by Mockito 5.4.6 from annotations
// in dadytube/test/services/youtube_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:youtube_explode_dart/src/channels/channels.dart' as _i4;
import 'package:youtube_explode_dart/src/playlists/playlist_client.dart' as _i3;
import 'package:youtube_explode_dart/src/search/search_client.dart' as _i5;
import 'package:youtube_explode_dart/src/videos/video.dart' as _i8;
import 'package:youtube_explode_dart/src/videos/video_client.dart' as _i2;
import 'package:youtube_explode_dart/src/youtube_explode_base.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVideoClient_0 extends _i1.SmartFake implements _i2.VideoClient {
  _FakeVideoClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistClient_1 extends _i1.SmartFake
    implements _i3.PlaylistClient {
  _FakePlaylistClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChannelClient_2 extends _i1.SmartFake implements _i4.ChannelClient {
  _FakeChannelClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchClient_3 extends _i1.SmartFake implements _i5.SearchClient {
  _FakeSearchClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChannel_4 extends _i1.SmartFake implements _i4.Channel {
  _FakeChannel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChannelAbout_5 extends _i1.SmartFake implements _i4.ChannelAbout {
  _FakeChannelAbout_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChannelUploadsList_6 extends _i1.SmartFake
    implements _i4.ChannelUploadsList {
  _FakeChannelUploadsList_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChannelId_7 extends _i1.SmartFake implements _i4.ChannelId {
  _FakeChannelId_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ChannelCopyWith_8<$Res> extends _i1.SmartFake
    implements _i4.$ChannelCopyWith<$Res> {
  _Fake$ChannelCopyWith_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ChannelIdCopyWith_9<$Res> extends _i1.SmartFake
    implements _i4.$ChannelIdCopyWith<$Res> {
  _Fake$ChannelIdCopyWith_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [YoutubeExplode].
///
/// See the documentation for Mockito's code generation for more information.
class MockYoutubeExplode extends _i1.Mock implements _i6.YoutubeExplode {
  MockYoutubeExplode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VideoClient get videos =>
      (super.noSuchMethod(
            Invocation.getter(#videos),
            returnValue: _FakeVideoClient_0(this, Invocation.getter(#videos)),
          )
          as _i2.VideoClient);

  @override
  _i3.PlaylistClient get playlists =>
      (super.noSuchMethod(
            Invocation.getter(#playlists),
            returnValue: _FakePlaylistClient_1(
              this,
              Invocation.getter(#playlists),
            ),
          )
          as _i3.PlaylistClient);

  @override
  _i4.ChannelClient get channels =>
      (super.noSuchMethod(
            Invocation.getter(#channels),
            returnValue: _FakeChannelClient_2(
              this,
              Invocation.getter(#channels),
            ),
          )
          as _i4.ChannelClient);

  @override
  _i5.SearchClient get search =>
      (super.noSuchMethod(
            Invocation.getter(#search),
            returnValue: _FakeSearchClient_3(this, Invocation.getter(#search)),
          )
          as _i5.SearchClient);

  @override
  set videos(_i2.VideoClient? value) => super.noSuchMethod(
    Invocation.setter(#videos, value),
    returnValueForMissingStub: null,
  );

  @override
  set playlists(_i3.PlaylistClient? value) => super.noSuchMethod(
    Invocation.setter(#playlists, value),
    returnValueForMissingStub: null,
  );

  @override
  set channels(_i4.ChannelClient? value) => super.noSuchMethod(
    Invocation.setter(#channels, value),
    returnValueForMissingStub: null,
  );

  @override
  set search(_i5.SearchClient? value) => super.noSuchMethod(
    Invocation.setter(#search, value),
    returnValueForMissingStub: null,
  );

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ChannelClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelClient extends _i1.Mock implements _i4.ChannelClient {
  MockChannelClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Channel> get(dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#get, [id]),
            returnValue: _i7.Future<_i4.Channel>.value(
              _FakeChannel_4(this, Invocation.method(#get, [id])),
            ),
          )
          as _i7.Future<_i4.Channel>);

  @override
  _i7.Future<_i4.Channel> getByUsername(dynamic username) =>
      (super.noSuchMethod(
            Invocation.method(#getByUsername, [username]),
            returnValue: _i7.Future<_i4.Channel>.value(
              _FakeChannel_4(
                this,
                Invocation.method(#getByUsername, [username]),
              ),
            ),
          )
          as _i7.Future<_i4.Channel>);

  @override
  _i7.Future<_i4.Channel> getByHandle(dynamic handle) =>
      (super.noSuchMethod(
            Invocation.method(#getByHandle, [handle]),
            returnValue: _i7.Future<_i4.Channel>.value(
              _FakeChannel_4(this, Invocation.method(#getByHandle, [handle])),
            ),
          )
          as _i7.Future<_i4.Channel>);

  @override
  _i7.Future<_i4.ChannelAbout> getAboutPage(dynamic channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getAboutPage, [channelId]),
            returnValue: _i7.Future<_i4.ChannelAbout>.value(
              _FakeChannelAbout_5(
                this,
                Invocation.method(#getAboutPage, [channelId]),
              ),
            ),
          )
          as _i7.Future<_i4.ChannelAbout>);

  @override
  _i7.Future<_i4.ChannelAbout> getAboutPageByUsername(dynamic username) =>
      (super.noSuchMethod(
            Invocation.method(#getAboutPageByUsername, [username]),
            returnValue: _i7.Future<_i4.ChannelAbout>.value(
              _FakeChannelAbout_5(
                this,
                Invocation.method(#getAboutPageByUsername, [username]),
              ),
            ),
          )
          as _i7.Future<_i4.ChannelAbout>);

  @override
  _i7.Future<_i4.Channel> getByVideo(dynamic videoId) =>
      (super.noSuchMethod(
            Invocation.method(#getByVideo, [videoId]),
            returnValue: _i7.Future<_i4.Channel>.value(
              _FakeChannel_4(this, Invocation.method(#getByVideo, [videoId])),
            ),
          )
          as _i7.Future<_i4.Channel>);

  @override
  _i7.Stream<_i8.Video> getUploads(dynamic channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getUploads, [channelId]),
            returnValue: _i7.Stream<_i8.Video>.empty(),
          )
          as _i7.Stream<_i8.Video>);

  @override
  _i7.Future<_i4.ChannelUploadsList> getUploadsFromPage(
    dynamic channelId, {
    _i4.VideoSorting? videoSorting = _i4.VideoSorting.newest,
    _i4.VideoType? videoType = _i4.VideoType.normal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUploadsFromPage,
              [channelId],
              {#videoSorting: videoSorting, #videoType: videoType},
            ),
            returnValue: _i7.Future<_i4.ChannelUploadsList>.value(
              _FakeChannelUploadsList_6(
                this,
                Invocation.method(
                  #getUploadsFromPage,
                  [channelId],
                  {#videoSorting: videoSorting, #videoType: videoType},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.ChannelUploadsList>);
}

/// A class which mocks [Channel].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannel extends _i1.Mock implements _i4.Channel {
  MockChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#url)),
          )
          as String);

  @override
  _i4.ChannelId get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _FakeChannelId_7(this, Invocation.getter(#id)),
          )
          as _i4.ChannelId);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  String get logoUrl =>
      (super.noSuchMethod(
            Invocation.getter(#logoUrl),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#logoUrl),
            ),
          )
          as String);

  @override
  String get bannerUrl =>
      (super.noSuchMethod(
            Invocation.getter(#bannerUrl),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#bannerUrl),
            ),
          )
          as String);

  @override
  _i4.$ChannelCopyWith<_i4.Channel> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$ChannelCopyWith_8<_i4.Channel>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i4.$ChannelCopyWith<_i4.Channel>);
}

/// A class which mocks [ChannelId].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelId extends _i1.Mock implements _i4.ChannelId {
  MockChannelId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#value),
            ),
          )
          as String);

  @override
  _i4.$ChannelIdCopyWith<_i4.ChannelId> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$ChannelIdCopyWith_9<_i4.ChannelId>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i4.$ChannelIdCopyWith<_i4.ChannelId>);
}
